### PR TITLE
fix: notify bot support message cards 

### PR DESCRIPTION
**Pull request by machinly**
Custom bot can send message cards, just cannot respond to interactions.

### CODE REVIEW

**Comment by crispgm** [comment]
Looks good, would u mind adding a test for that?

Just copy this: https://github.com/go-lark/lark/blob/main/api_message_test.go#L179

**Comment by machinly** [comment]
Reference: [Use bots in groups](https://www.feishu.cn/hc/en-US/articles/360024984973#lineguid-NchfLO)  3.4. Message cards

**Comment by machinly** [comment]
> Looks good, would u mind adding a test for that?
> 
> Just copy this: https://github.com/go-lark/lark/blob/main/api_message_test.go#L179

Happy to do that.

**Comment by machinly** [comment]
Done test. But there are still some remaining issues, #21 .

**Pull request merged**
