### PR TITLE
feat(api): UploadBinaryFile support uploads binary file

### PR DESCRIPTION
**Pull request by wahwahid**
We usually need to upload system generated virtual files that contains dynamic data.

### CODE REVIEW

**Comment by crispgm** [comment]
Looks good.

Would you mind showing me the document from lark platform? I want to the usage. Thanks.

**Comment by wahwahid** [comment]
Actually UploadBinaryFile share same API with UploadFile.
https://open.feishu.cn/document/server-docs/im-v1/file/create

The differentiation when UploadFile lookup a file based on path provided in the argument then load the content, UploadBinaryFile retrieve file content via `io.Reader` directly.

**Comment by crispgm** [comment]
> Actually UploadBinaryFile share same API with UploadFile. https://open.feishu.cn/document/server-docs/im-v1/file/create
> 
> The differentiation when UploadFile lookup a file based on path provided in the argument then load the content, UploadBinaryFile retrieve file content via `io.Reader` directly.

I think it not necessary to create a new method. Maybe just add a parameter in the request?

**Comment by wahwahid** [comment]
I was thinking about that too, but i follow what UploadImage & UploadImageObject do.
They also share same API but have different input.
What do you think, wasn't this PR follow the project approach to have isolated and clear method ?

But if change to one method with additional parameter, i have a question.
How we decide between path / binary ?
1. Make the reader pointer, check the reader, use path when the reader nil or
2. Check the path, use binary when the path empty ?
But, what happen if both empty ?
1. Return error from our package side ?

**Comment by crispgm** [comment]
> I was thinking about that too, but i follow what UploadImage & UploadImageObject do. They also share same API but have different input. What do you think, wasn't this PR follow the project approach to have isolated and clear method ?
> 
> If change to one method with additional parameter, i have a question. How we decide between path / binary ?
> 
>     1. Make the reader pointer, check the reader, use path when the reader nil or
> 
>     2. Check the path, use binary when the path empty ?
> 
> 
> But, what happen if both empty ?
> 
>     1. Return error from our package side ?

The `UploadImageObject` is an old-school method, which was not reviewed carefully and then migrated from in-house repo to GitHub. We may also remove `UploadImageObject` then.

Maybe change both into pointers and check which is not nil.

**Comment by wahwahid** [comment]
Hi @crispgm please check another PR related to changes here: https://github.com/go-lark/lark/pull/72

**Pull request closed without merging**
